version: "3"
services:
  ansible_tower:
    privileged: true
    container_name: 'ansible_tower_server'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: ansible_pg
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ansible}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ansible_pwd}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
